/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import javax.swing.JFrame;
import metier.Medicament;

/**
 *
 * @author Steve Maingana
 */
public class JdAvis extends javax.swing.JDialog {
    private Medicament medicament;

    /**
     * Constructeur de la classe JdAvis, qui est une JDialog
     * @param parent Fenêtre associée à la boîte de dialogue
     * @param modal Booléen vérifiant la modalité de la boîte de dialogue par rapport aux autres fenêtres
     * @param medicament Médicament dont les avis sont affichés
     * @param message Liste des avis à afficher dans la boîte de dialogue
     */
    public JdAvis(JFrame parent, boolean modal, Medicament medicament, String message) {
        // Référence du constructeur de la classe mère JDialog
        super(parent, modal);
        initComponents();
        this.medicament = medicament;
        
        // Centralisation de la position de la JDialog par rapport à la fenêtre associée
        this.setLocationRelativeTo(parent);
        
        // Affichage de tous les commentaires du medicament
        jLAvis.setText("Tous les avis sur le "+medicament.getNom());
        jTAAvis.setText(message);
        jTAAvis.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAvis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAAvis = new javax.swing.JTextArea();
        jBtFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Commentaires");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLAvis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAvis.setText("Avis sur ...");
        getContentPane().add(jLAvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, -1));

        jTAAvis.setEditable(false);
        jTAAvis.setColumns(20);
        jTAAvis.setRows(5);
        jTAAvis.setFocusable(false);
        jScrollPane1.setViewportView(jTAAvis);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 420, 280));

        jBtFermer.setText("Fermer");
        jBtFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFermerActionPerformed(evt);
            }
        });
        getContentPane().add(jBtFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action effectuée lorsque l'utilisateur clique sur le bouton "Fermer"
     * Cette méthode ferme la fenêtre
     * @param evt : L'événement d'action déclenché par le clic sur le bouton
     */
    private void jBtFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFermerActionPerformed
        // Fermeture de la fenêtre
        this.dispose();
    }//GEN-LAST:event_jBtFermerActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdAvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdAvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdAvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdAvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtFermer;
    private javax.swing.JLabel jLAvis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAAvis;
    // End of variables declaration//GEN-END:variables
}
